default_config:

logger:
  default: info
  logs:
    custom_components.ovms_trips_recorder: debug
    custom_components.ovms: debug

homeassistant:
  name: Trips Recorder Dev
  unit_system: metric
  time_zone: Europe/Paris
